#!/bin/bash

# Configuration variables - edit these to change directories
HYPERSIM_DIR="/YOUR HYPERSIM DIR HERE/data/hypersim/"
DESTINATION_DIR="/YOUR DESTINATION DIR HERE/data/hypersim-pointclouds/"

python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_001_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_001_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_001_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_001_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_001_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_001_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_001_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_001_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_001_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_002_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_002_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_002_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_002_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_002_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_002_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_002_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_002_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_002_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_003_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_003_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_003_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_003_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_003_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_003_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_004_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_004_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_004_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_004_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_004_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_004_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_004_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_004_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_005_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_005_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_005_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_005_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_005_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_005_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_006_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_006_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_006_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_006_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_006_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_006_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_007_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_007_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_007_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_007_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_007_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_007_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_007_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_008_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_008_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_008_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_008_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_008_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_008_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_008_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_009_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_009_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_009_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_009_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_009_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_009_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_009_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_010_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_010_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_010_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_010_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_010_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_010_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_010_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_011_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_011_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_011_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_011_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_011_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_011_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_011_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_012_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_012_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_012_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_012_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_012_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_013_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_013_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_013_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_013_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_014_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_014_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_015_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_015_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_015_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_015_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_015_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_015_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_015_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_016_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_016_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_016_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_016_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_016_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_016_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_016_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_016_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_017_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_017_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_017_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_017_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_017_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_017_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_017_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_017_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_017_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_018_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_018_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_018_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_018_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_018_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_018_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_018_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_018_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_018_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_019_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_019_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_019_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_019_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_019_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_019_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_019_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_019_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_021_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_021_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_021_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_021_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_021_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_021_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_021_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_022_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_022_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_022_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_022_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_022_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_022_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_022_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_022_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_022_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_023_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_023_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_023_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_023_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_023_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_023_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_023_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_011 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_012 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_014 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_017 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_019 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_011 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_012 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_013 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_015 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_016 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_017 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_018 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_020 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_027_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_027_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_027_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_027_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_027_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_027_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_027_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_028_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_028_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_028_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_028_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_028_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_029_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_029_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_029_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_029_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_030_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_030_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_030_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_030_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_030_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_030_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_030_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_031_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_031_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_031_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_031_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_031_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_031_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_032_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_032_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_032_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_032_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_032_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_032_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_032_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_032_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_033_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_033_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_033_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_033_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_033_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_033_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_033_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_034_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_034_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_034_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_034_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_035_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_035_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_035_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_035_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_035_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_035_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_035_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_035_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_035_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_036_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_036_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_036_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_036_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_036_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_036_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_037_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_037_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_037_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_037_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_037_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_037_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_037_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_037_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_038_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_038_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_038_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_038_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_039_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_039_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_039_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_039_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_039_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_039_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_039_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_039_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_039_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_041_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_041_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_041_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_041_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_041_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_041_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_041_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_041_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_042_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_042_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_042_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_042_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_043_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_043_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_043_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_043_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_043_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_043_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_043_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_043_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_044_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_044_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_044_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_044_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_044_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_044_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_044_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_044_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_044_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_045_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_045_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_045_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_045_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_045_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_045_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_046_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_046_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_046_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_046_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_046_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_046_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_046_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_047_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_047_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_047_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_047_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_047_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_047_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_047_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_047_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_048_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_048_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_048_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_048_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_048_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_048_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_048_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_048_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_048_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_050_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_050_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_050_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_050_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_050_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_051_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_051_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_052_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_052_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_052_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_052_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_052_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_052_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_052_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_052_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_052_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_012 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_013 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_016 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_017 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_020 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_054_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_054_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_054_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_054_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_054_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_054_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_054_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_055_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_055_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_055_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_055_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_055_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_055_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_001_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_002_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_003_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_003_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_005_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_006_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_006_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_007_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_008_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_009_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_009_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_011_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_011_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_012_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_013_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_014_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_015_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_016_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_023_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_016 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_018 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_019 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_028_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_029_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_030_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_033_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_036_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_037_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_037_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_038_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_038_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_041_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_041_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_042_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_043_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_048_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_051_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_051_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_014 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_018 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_054_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_055_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_055_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_055_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_003_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_004_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_004_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_005_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_005_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_006_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_007_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_008_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_008_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_010_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_010_002 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_013_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_013_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_015_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_017_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_018_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_023_004 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_023_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_013 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_024_015 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_026_014 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_027_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_027_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_028_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_028_006 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_030_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_031_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_031_010 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_035_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_036_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_038_007 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_044_009 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_046_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_047_005 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_051_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_052_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_053_019 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_054_001 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_054_008 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
python scripts/open3d_make_pointcloud.py --hypersim-dir "${HYPERSIM_DIR}" --scene ai_055_003 --destination "${DESTINATION_DIR}" --num-files 100 --voxel-size 0.00125 --verbose
